### PR TITLE
:sparkles: Made the message in the popup menu customizable

### PR DESCRIPTION
**Pull request by djinnalexio**

### CODE REVIEW

**Comment by lyrahgames** [comment]
Thank you very much for your work and for adding this functionality.
I very much appreciate the help and the corrections, as I did not really have the time for it the last few months.

As it is stated in `metadata.json`, you presumably automatically generated it.
I am not using any generator and the key `_generated` does not make any sense in my environment.
Hence, I will probably remove it at some point.

I will merge your changes and update the version on Gnome Hub.

**Comment by djinnalexio** [comment]
You're welcome.

I'm curious. What environment do you use? In my case, I simply use VS code.

**Comment by lyrahgames** [comment]
Oh, I am also only using Sublime Text as my editor.
But looking in `metadata.json`, it seemed to me the file would have been automatically generated by some tool.
Otherwise, what does the key `_generated` and its value stand for?

**Comment by djinnalexio** [comment]
I didn't generate it either. I'm just copying and editing a template I've seen in other extensions.  
`_generated` only shows if the file was automatically created and by which program. Since this value is never called, including it or deleting it will not affect anything. I just pretend it was generated.

**Comment by lyrahgames** [comment]
I see. Then my inference was wrong. Thanks for the clarification.
Presumably, I will then remove it in the next commit.

**Pull request merged**
